import type { Metadata } from "next";
import "./globals.styles";
import { Page } from "./layout.styles";
import Navbar from "./components/Navbar/Navbar";
import { GlobalStyles } from "./globals.styles";
import StyledComponentsRegistry from "./lib/registry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <GlobalStyles />
        <StyledComponentsRegistry>
          <Navbar />
          <Page>{children}</Page>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
