import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.styles";
import { Page } from "./layout.styles";
import Navbar from "./components/Navbar/Navbar";
import { Body } from "./globals.styles";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en">
      <Body>
        <Navbar />
        <Page>{children}</Page>
      </Body>
    </html>
  );
}
